namespace MoneyManager.Data;

/// <summary>
/// Represents a historical balance snapshot for an account.
/// </summary>
/// <remarks>
/// Balances are used to track account value over time for trend analysis and net worth calculations.
/// They can be imported from statements or manually entered.
/// Supports visualization of balance history in charts.
/// </remarks>
public class Balance
{
    /// <summary>
    /// Gets or sets the unique identifier for this balance record.
    /// </summary>
    /// <value>
    /// The primary key for the balance entity. This value is auto-generated by the database.
    /// </value>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the account associated with this balance snapshot.
    /// </summary>
    /// <value>
    /// The <see cref="Account"/> whose balance is being recorded.
    /// </value>
    /// <remarks>
    /// This establishes a many-to-one relationship with the Accounts table.
    /// Allows for tracking balance history across multiple accounts.
    /// </remarks>
    public Account? Account { get; set; }

    /// <summary>
    /// Gets or sets the date when the balance was recorded.
    /// </summary>
    /// <value>
    /// The date of the balance snapshot.
    /// </value>
    /// <remarks>
    /// Used for chronological ordering and time-series analysis.
    /// Typically represents month-end or statement dates.
    /// </remarks>
    public DateTime Date { get; set; }

    /// <summary>
    /// Gets or sets the account balance amount at the specified date.
    /// </summary>
    /// <value>
    /// The monetary value of the account on the recorded date.
    /// </value>
    /// <remarks>
    /// Positive values represent money in the account.
    /// Used for balance trend visualization and net worth calculations.
    /// Can be compared to transaction totals for reconciliation.
    /// </remarks>
    public decimal Amount { get; set; }
}
