using Icon = Microsoft.FluentUI.AspNetCore.Components.Icon;

namespace MoneyManager.Data;

/// <summary>
/// Represents a category for classifying financial transactions in the MoneyManager system.
/// </summary>
/// <remarks>
/// Categories support a hierarchical structure where categories can have parent-child relationships.
/// Top-level categories have icons; child categories inherit their parent's icon.
/// Used for transaction classification, budgeting, and spending analysis.
/// The "Transfer" category is specifically filtered from spending charts.
/// The "Income" category is treated specially in financial calculations.
/// </remarks>
public class Category
{
    /// <summary>
    /// Gets or sets the unique identifier for the category.
    /// </summary>
    /// <value>
    /// The primary key for the category entity. This value is auto-generated by the database.
    /// </value>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the parent category in the hierarchical structure.
    /// </summary>
    /// <value>
    /// The parent <see cref="Category"/> if this is a subcategory, or null if this is a top-level category.
    /// </value>
    /// <remarks>
    /// Establishes a self-referencing many-to-one relationship.
    /// Child categories inherit the parent's icon for display purposes.
    /// </remarks>
    public Category? Parent { get; set; }

    /// <summary>
    /// Gets or sets the display name of the category.
    /// </summary>
    /// <value>
    /// The human-readable name for the category.
    /// </value>
    /// <remarks>
    /// Must be unique at the same hierarchy level.
    /// Used for dropdown displays and filtering.
    /// </remarks>
    public string Name { get; set; } = null!;

    /// <summary>
    /// Gets or sets the icon identifier for this category.
    /// </summary>
    /// <value>
    /// The name of the icon enum value (e.g., "Food", "Home"), or null for subcategories.
    /// </value>
    /// <remarks>
    /// Only top-level categories should have icons set.
    /// Child categories inherit the parent's icon.
    /// Icons are mapped to Fluent UI icons via <see cref="CategoryHelper"/>.
    /// </remarks>
    public string? Icon { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether this category was auto-created during transaction import.
    /// </summary>
    /// <value>
    /// <c>true</c> if category was created automatically during import; otherwise, <c>false</c>.
    /// </value>
    /// <remarks>
    /// Helps users identify categories that may need review or reorganization.
    /// Can be used to clean up auto-generated categories after import.
    /// </remarks>
    public bool IsNew { get; set; }

    /// <summary>
    /// Gets the icon identifier for display (inherited from parent if this is a subcategory).
    /// </summary>
    /// <value>
    /// The icon string from the parent category if this has a parent, or its own icon if it's a top-level category.
    /// </value>
    /// <remarks>
    /// Computed property. Ensures subcategories display the same icon as their parent.
    /// </remarks>
    public string? pIcon => Parent == null ? Icon : Parent.Icon;

    /// <summary>
    /// Gets the Fluent UI icon object for this category.
    /// </summary>
    /// <value>
    /// A <see cref="Icon"/> object representing the visual indicator for this category.
    /// </value>
    /// <remarks>
    /// Computed property. Delegates to <see cref="CategoryHelper.CategoryIcon(string)"/> for icon resolution.
    /// Subcategories inherit their parent's icon.
    /// </remarks>
    public Icon objIcon => CategoryHelper.CategoryIcon(Parent == null ? Icon : Parent.Icon);

    /// <summary>
    /// Returns the display name of the category.
    /// </summary>
    /// <returns>
    /// The <see cref="Name"/> of the category.
    /// </returns>
    public override string ToString() => Name;
}

/// <summary>
/// Represents a hierarchical category tree structure for display and selection.
/// </summary>
/// <remarks>
/// Used to represent category hierarchies in the UI with support for nested children.
/// Useful for category selection dialogs and tree view displays.
/// </remarks>
public class CategoryTree
{
    /// <summary>
    /// Gets the unique identifier of the category.
    /// </summary>
    public int Id { get; init; }

    /// <summary>
    /// Gets or sets the display name of the category.
    /// </summary>
    public string Name { get; set; } = null!;

    /// <summary>
    /// Gets or sets the icon identifier for the category.
    /// </summary>
    public string? Icon { get; set; }

    /// <summary>
    /// Gets the collection of child categories in the hierarchy.
    /// </summary>
    /// <value>
    /// A HashSet of <see cref="CategoryTree"/> objects representing child categories.
    /// </value>
    public HashSet<CategoryTree> Children { get; init; } = [];

    /// <summary>
    /// Gets or sets the parent category in the tree structure.
    /// </summary>
    public CategoryTree? Parent { get; set; }

    /// <summary>
    /// Returns the display name of the category.
    /// </summary>
    /// <returns>
    /// The <see cref="Name"/> of the category.
    /// </returns>
    public override string ToString() => Name;
}

/// <summary>
/// Represents a category item for use in dropdown selectors.
/// </summary>
/// <remarks>
/// Flattens category hierarchy for display in dropdown controls.
/// Includes parent category name for context when selecting subcategories.
/// </remarks>
public class CategoryDropItem(Category c, string parentId)
{
    /// <summary>
    /// Gets the unique identifier of the category.
    /// </summary>
    public int Id { get; } = c.Id;

    /// <summary>
    /// Gets the display name of the category.
    /// </summary>
    public string Name { get; } = c.Name;

    /// <summary>
    /// Gets or sets the parent category name for display context.
    /// </summary>
    /// <value>
    /// The name of the parent category, or an empty string if this is a top-level category.
    /// </value>
    /// <remarks>
    /// Helps users distinguish between subcategories with similar names from different parents.
    /// </remarks>
    public string ParentCategory { get; set; } = parentId;

    /// <summary>
    /// Returns the display name of the category.
    /// </summary>
    /// <returns>
    /// The <see cref="Name"/> of the category.
    /// </returns>
    public override string ToString() => Name;
}

/// <summary>
/// Provides helper methods for working with categories and icons.
/// </summary>
public static class CategoryHelper
{
    /// <summary>
    /// Gets the list of available category icon names.
    /// </summary>
    /// <value>
    /// A list of strings representing the names in the <see cref="CategoryIconEnum"/> enumeration.
    /// </value>
    /// <remarks>
    /// Used for populating dropdown selectors with available icon options.
    /// </remarks>
    public static List<string> CategoryIcons => Enum.GetNames(typeof(CategoryIconEnum)).ToList();

    /// <summary>
    /// Gets the appropriate Fluent UI icon for a given category icon name.
    /// </summary>
    /// <param name="icon">The icon name string (e.g., "Food", "Home").</param>
    /// <returns>
    /// A <see cref="Icon"/> object representing the specified category icon.
    /// </returns>
    /// <remarks>
    /// If the icon string is null or whitespace, returns the "BorderNone" icon.
    /// Attempts to parse the string to a <see cref="CategoryIconEnum"/>; falls back to "Uncategorized" if parsing fails.
    /// </remarks>
    public static Icon CategoryIcon(string? icon) => string.IsNullOrWhiteSpace(icon)
        ? new  Icons.Regular.Size20.BorderNone()
        : CategoryIcon(Enum.TryParse(icon, out CategoryIconEnum categoryIcon) ? categoryIcon : CategoryIconEnum.Uncategorized);

    /// <summary>
    /// Gets the appropriate Fluent UI icon for a given category icon enum value.
    /// </summary>
    /// <param name="icon">The <see cref="CategoryIconEnum"/> value.</param>
    /// <returns>
    /// A <see cref="Icon"/> object representing the specified category icon.
    /// </returns>
    /// <remarks>
    /// Maps each category icon to a specific Fluent UI icon.
    /// Supports 22 different icon types for various expense categories.
    /// </remarks>
    private static Icon CategoryIcon(CategoryIconEnum icon) => icon switch
    {
        CategoryIconEnum.Auto => new Icons.Filled.Size20.VehicleCarProfile(),
        CategoryIconEnum.Bills => new Icons.Filled.Size20.Lightbulb(),
        CategoryIconEnum.Business => new Icons.Regular.Size20.Briefcase(),
        CategoryIconEnum.Education => new Icons.Regular.Size20.HatGraduation(),
        CategoryIconEnum.Entertainment => new Icons.Regular.Size20.MoviesAndTv(),
        CategoryIconEnum.Fees => new Icons.Regular.Size20.MoneyHand(),
        CategoryIconEnum.Financial => new Icons.Regular.Size20.BuildingBank(),
        CategoryIconEnum.Food => new Icons.Regular.Size20.Food(),
        CategoryIconEnum.Gifts => new Icons.Regular.Size20.Gift(),
        CategoryIconEnum.Health => new Icons.Regular.Size20.Doctor(),
        CategoryIconEnum.Home => new Icons.Regular.Size20.Home(),
        CategoryIconEnum.Income => new Icons.Filled.Size20.Money(),
        CategoryIconEnum.Investment => new Icons.Filled.Size20.ArrowTrendingLines(),
        CategoryIconEnum.Kids => new Icons.Filled.Size20.PersonRunning(),
        CategoryIconEnum.Loans => new Icons.Filled.Size20.Handshake(),
        CategoryIconEnum.Misc => new Icons.Filled.Size20.PuzzlePiece(),
        CategoryIconEnum.Personal => new Icons.Filled.Size20.PersonHeart(),
        CategoryIconEnum.Pets => new Icons.Filled.Size20.AnimalCat(),
        CategoryIconEnum.Shopping => new Icons.Filled.Size20.Cart(),
        CategoryIconEnum.Taxes => new Icons.Filled.Size20.DocumentPercent(),
        CategoryIconEnum.Transfer => new Icons.Filled.Size20.ArrowSwap(),
        CategoryIconEnum.Travel => new Icons.Filled.Size20.AirplaneTakeOff(),
        _ => new Icons.Regular.Size20.StackStar()
    };
}

/// <summary>
/// Enumeration of available category icon types.
/// </summary>
/// <remarks>
/// Maps categories to visual icons in the UI.
/// Used for consistent and intuitive representation of expense categories.
/// Icons are mapped to Fluent UI components in <see cref="CategoryHelper"/>.
/// </remarks>
public enum CategoryIconEnum
{
    /// <summary>Automotive and transportation expenses (gas, maintenance, car payments)</summary>
    Auto,
    /// <summary>Utility bills and recurring payments (electricity, water, internet)</summary>
    Bills,
    /// <summary>Business-related expenses and income</summary>
    Business,
    /// <summary>Educational expenses (tuition, books, courses)</summary>
    Education,
    /// <summary>Entertainment and leisure (movies, games, events)</summary>
    Entertainment,
    /// <summary>Banking and transaction fees, penalties</summary>
    Fees,
    /// <summary>Financial services, banking, and investment-related expenses</summary>
    Financial,
    /// <summary>Food and dining (groceries, restaurants, takeout)</summary>
    Food,
    /// <summary>Gifts and charitable giving</summary>
    Gifts,
    /// <summary>Health and medical expenses (doctor, pharmacy, insurance)</summary>
    Health,
    /// <summary>Home and housing (rent, mortgage, maintenance, supplies)</summary>
    Home,
    /// <summary>Income category (salary, bonuses, other income sources)</summary>
    Income,
    /// <summary>Investments and portfolio-related transactions</summary>
    Investment,
    /// <summary>Child-related expenses (childcare, activities, toys)</summary>
    Kids,
    /// <summary>Loan payments and debt repayment</summary>
    Loans,
    /// <summary>Miscellaneous and uncategorized expenses</summary>
    Misc,
    /// <summary>Personal care and wellness (gym, salon, personal items)</summary>
    Personal,
    /// <summary>Pet-related expenses (veterinary, food, supplies)</summary>
    Pets,
    /// <summary>Retail shopping (clothing, electronics, household goods)</summary>
    Shopping,
    /// <summary>Tax payments and government fees</summary>
    Taxes,
    /// <summary>Internal money transfers between accounts</summary>
    Transfer,
    /// <summary>Travel and vacation expenses (flights, hotels, tours)</summary>
    Travel,
    /// <summary>Default category for uncategorized transactions</summary>
    Uncategorized
}
