using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MoneyManager.Api.Data;

/// <summary>
/// Represents a financial account in the MoneyManager system, such as bank accounts, credit cards, or investment accounts.
/// </summary>
/// <remarks>
/// Accounts support alternative names for flexible matching during CSV imports from different banks.
/// The Type property determines which icon is displayed in the UI.
/// </remarks>
public class Account
{
    /// <summary>
    /// Gets or sets the unique identifier for the account.
    /// </summary>
    /// <value>
    /// The primary key for the account entity. This value is auto-generated by the database.
    /// </value>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the original name of the account as provided by the bank during import.
    /// </summary>
    /// <value>
    /// The name from the bank's CSV export. This name is used for matching transactions during imports.
    /// This field is required and cannot be null.
    /// </value>
    /// <remarks>
    /// This is the raw name from the bank. For display purposes, use the <see cref="ShownName"/> property.
    /// </remarks>
    public string Name { get; set; } = null!;

    /// <summary>
    /// Gets or sets the user-friendly display name for the account.
    /// </summary>
    /// <value>
    /// The name shown to users in the UI. This can be customized and may differ from the original bank name.
    /// This field is required and cannot be null.
    /// </value>
    /// <remarks>
    /// Users can change this to something more meaningful, such as "Checking Account" instead of "RBC Chequing 1234".
    /// </remarks>
    public string ShownName { get; set; } = null!;

    /// <summary>
    /// Gets or sets an optional description for the account.
    /// </summary>
    /// <value>
    /// Additional information about the account, or null if no description is provided.
    /// </value>
    /// <remarks>
    /// This can be used to store notes or details about the account's purpose.
    /// </remarks>
    public string? Description { get; set; }

    /// <summary>
    /// Gets or sets the type of account (Cash, Credit Card, Investment, or Other).
    /// </summary>
    /// <value>
    /// An integer representing the account type:
    /// <list type="bullet">
    /// <item><description>0 - Cash</description></item>
    /// <item><description>1 - Credit Card</description></item>
    /// <item><description>2 - Investment</description></item>
    /// <item><description>3 - Other</description></item>
    /// </list>
    /// </value>
    /// <remarks>
    /// The type determines which icon is displayed in the UI via the <see cref="TypeIconName"/> property.
    /// </remarks>
    public int Type { get; set; }

    /// <summary>
    /// Gets or sets the account number from the bank.
    /// </summary>
    /// <value>
    /// The account number as a string, or null if not available.
    /// </value>
    /// <remarks>
    /// This number is used for matching transactions during imports, especially when combined with dashes removed.
    /// </remarks>
    public string? Number { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether this account should be excluded from spending charts and visualizations.
    /// </summary>
    /// <value>
    /// <c>true</c> if the account is hidden from graphs; otherwise, <c>false</c>.
    /// </value>
    /// <remarks>
    /// Useful for accounts like "Transfer" or internal accounts that shouldn't affect financial analysis.
    /// </remarks>
    public bool IsHideFromGraph { get; set; }

    /// <summary>
    /// Gets or sets an alternative account name for matching during CSV imports.
    /// </summary>
    /// <value>
    /// An alternative name to match against import data, or null if not specified.
    /// </value>
    /// <remarks>
    /// Banks may use different names for the same account over time. This allows flexible matching.
    /// Matching is case-insensitive.
    /// </remarks>
    public string? AlternativeName1 { get; set; }

    /// <summary>
    /// Gets or sets a second alternative account name for matching during CSV imports.
    /// </summary>
    /// <value>
    /// An alternative name to match against import data, or null if not specified.
    /// </value>
    /// <remarks>
    /// Supports up to 5 alternative names to handle various naming conventions from banks.
    /// </remarks>
    public string? AlternativeName2 { get; set; }

    /// <summary>
    /// Gets or sets a third alternative account name for matching during CSV imports.
    /// </summary>
    /// <value>
    /// An alternative name to match against import data, or null if not specified.
    /// </value>
    public string? AlternativeName3 { get; set; }

    /// <summary>
    /// Gets or sets a fourth alternative account name for matching during CSV imports.
    /// </summary>
    /// <value>
    /// An alternative name to match against import data, or null if not specified.
    /// </value>
    public string? AlternativeName4 { get; set; }

    /// <summary>
    /// Gets or sets a fifth alternative account name for matching during CSV imports.
    /// </summary>
    /// <value>
    /// An alternative name to match against import data, or null if not specified.
    /// </value>
    public string? AlternativeName5 { get; set; }

    /// <summary>
    /// Gets the Lucide icon name that corresponds to the account type for the React frontend.
    /// </summary>
    /// <value>
    /// A string representing the Lucide icon name for this account type.
    /// </value>
    /// <remarks>
    /// This property is not mapped to the database and is computed dynamically based on the <see cref="Type"/> property.
    /// </remarks>
    [NotMapped]
    public string TypeIconName => AccountHelper.TypeIconName(Type);

    /// <summary>
    /// Returns the display name of the account.
    /// </summary>
    /// <returns>
    /// The <see cref="ShownName"/> of the account.
    /// </returns>
    public override string ToString() => ShownName;
}

/// <summary>
/// Provides helper methods for working with accounts.
/// </summary>
public static class AccountHelper
{
    /// <summary>
    /// Gets the appropriate Lucide icon name for a given account type.
    /// </summary>
    /// <param name="accountType">The account type (0=Cash, 1=CreditCard, 2=Investment, other=Other).</param>
    /// <returns>
    /// A string representing the Lucide icon name for the specified account type.
    /// </returns>
    /// <remarks>
    /// <list type="table">
    /// <item><term>Cash (0)</term><description>hand-coins icon</description></item>
    /// <item><term>Credit Card (1)</term><description>credit-card icon</description></item>
    /// <item><term>Investment (2)</term><description>trending-up icon</description></item>
    /// <item><term>Other (3+)</term><description>circle-dollar-sign icon</description></item>
    /// </list>
    /// </remarks>
    public static string TypeIconName(int accountType) => accountType switch
    {
        0 => "hand-coins",        // Cash
        1 => "credit-card",       // Credit Card
        2 => "trending-up",       // Investment
        _ => "circle-dollar-sign" // Other
    };
}
