using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MoneyManager.Api.Data;

/// <summary>
/// Represents an AI service provider configuration for financial analysis.
/// </summary>
/// <remarks>
/// Stores connection details and credentials for AI providers used by the application.
/// Supports multiple provider types including OpenAI, ZAI, and custom endpoints.
/// API keys are stored encrypted via ASP.NET Data Protection.
/// Only one provider should be marked as <see cref="IsDefault"/> at a time.
/// </remarks>
public class AiProvider
{
    /// <summary>
    /// Gets or sets the unique identifier for this AI provider configuration.
    /// </summary>
    /// <value>
    /// The primary key for the AI provider entity. This value is auto-generated by the database.
    /// </value>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the display name of the AI provider.
    /// </summary>
    /// <value>
    /// A human-readable name for this provider configuration (e.g., "My OpenAI Key").
    /// This field is required and cannot be null.
    /// </value>
    public string Name { get; set; } = null!;

    /// <summary>
    /// Gets or sets the type of AI provider.
    /// </summary>
    /// <value>
    /// A string identifying the provider type: "OpenAI", "ZAI", or "Custom".
    /// This field is required and cannot be null.
    /// </value>
    public string ProviderType { get; set; } = null!;

    /// <summary>
    /// Gets or sets the encrypted API key for authenticating with the provider.
    /// </summary>
    /// <value>
    /// The API key encrypted via ASP.NET Data Protection. This field is required and cannot be null.
    /// </value>
    /// <remarks>
    /// Never store or transmit the raw API key. Use the encryption service to protect and unprotect this value.
    /// </remarks>
    public string EncryptedApiKey { get; set; } = null!;

    /// <summary>
    /// Gets or sets the base URL for the AI provider's API endpoint.
    /// </summary>
    /// <value>
    /// The full URL for the provider's API (e.g., "https://api.openai.com/v1").
    /// This field is required and cannot be null.
    /// </value>
    public string ApiUrl { get; set; } = null!;

    /// <summary>
    /// Gets or sets the AI model identifier to use with this provider.
    /// </summary>
    /// <value>
    /// The model name (e.g., "gpt-4o", "gpt-3.5-turbo"). This field is required and cannot be null.
    /// </value>
    public string Model { get; set; } = null!;

    /// <summary>
    /// Gets or sets a value indicating whether this is the default AI provider.
    /// </summary>
    /// <value>
    /// <c>true</c> if this provider should be used by default for AI operations; otherwise, <c>false</c>.
    /// </value>
    /// <remarks>
    /// Only one provider should be marked as default at any time.
    /// </remarks>
    public bool IsDefault { get; set; }

    /// <summary>
    /// Gets or sets the timestamp when this provider configuration was created.
    /// </summary>
    /// <value>
    /// The UTC date and time of creation. Defaults to the current UTC time.
    /// </value>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
