using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MoneyManager.Api.Data;

/// <summary>
/// Represents an auto-categorization rule for automatically classifying transactions.
/// </summary>
/// <remarks>
/// Rules are applied to transactions during import or when manually triggered.
/// They match transaction descriptions against patterns and assign categories and can transform descriptions.
/// Rules are applied in the order they are defined in the database.
/// </remarks>
public class Rule
{
    /// <summary>
    /// Gets or sets the unique identifier for the rule.
    /// </summary>
    /// <value>
    /// The primary key for the rule entity. This value is auto-generated by the database.
    /// </value>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the pattern to match against transaction descriptions.
    /// </summary>
    /// <value>
    /// A string pattern used for matching against the <see cref="Transaction.OriginalDescription"/> of transactions.
    /// </value>
    /// <remarks>
    /// This is the "search" pattern. How it's matched depends on the <see cref="CompareType"/> property.
    /// Case-insensitive matching is applied.
    /// Example: "NETFLIX" to match transactions containing "Netflix".
    /// </remarks>
    public string OriginalDescription { get; set; } = null!;

    /// <summary>
    /// Gets or sets the replacement description to apply to matching transactions.
    /// </summary>
    /// <value>
    /// The new description to replace the original description on matching transactions.
    /// </value>
    /// <remarks>
    /// This is optional. If set, the transaction's <see cref="Transaction.Description"/> will be replaced with this value.
    /// If empty or null, the original description is preserved but the category is still assigned.
    /// Example: "Netflix Subscription" to standardize descriptions.
    /// </remarks>
    public string NewDescription { get; set; } = null!;

    /// <summary>
    /// Gets or sets the type of comparison to use when matching the pattern.
    /// </summary>
    /// <value>
    /// A <see cref="RuleCompareType"/> enum value specifying the matching algorithm.
    /// </value>
    /// <remarks>
    /// Determines how the <see cref="OriginalDescription"/> pattern is compared to transaction descriptions.
    /// Options include: Contains, StartsWith, EndsWith, and Equals.
    /// </remarks>
    public RuleCompareType CompareType { get; set; }

    /// <summary>
    /// Gets the string representation of the comparison type for display purposes.
    /// </summary>
    /// <value>
    /// The name of the <see cref="CompareType"/> enum value as a string.
    /// </value>
    /// <remarks>
    /// NotMapped property. Used for displaying the comparison type in the UI.
    /// </remarks>
    [NotMapped] public string CompareTypeString => CompareType.ToString();

    /// <summary>
    /// Gets or sets the category to assign to matching transactions.
    /// </summary>
    /// <value>
    /// The <see cref="Category"/> that will be assigned to transactions matching this rule.
    /// </value>
    /// <remarks>
    /// This is the "action" part of the rule. When a transaction matches the pattern,
    /// this category is assigned and the transaction's <see cref="Transaction.IsRuleApplied"/> flag is set to true.
    /// </remarks>
    public Category Category { get; set; } = null!;
}

/// <summary>
/// Enumeration of comparison types for rule matching.
/// </summary>
/// <remarks>
/// Defines the algorithms available for matching transaction descriptions against rule patterns.
/// </remarks>
public enum RuleCompareType
{
    /// <summary>
    /// Matches if the pattern is found anywhere within the transaction description.
    /// </summary>
    /// <example>
    /// Pattern: "LOBLAWS" matches "Loblaws Supermarket" and "Loblaws Pharmacy".
    /// </example>
    Contains,
    /// <summary>
    /// Matches if the transaction description starts with the pattern.
    /// </summary>
    /// <example>
    /// Pattern: "AMAZON" matches "Amazon Prime" but not "My Amazon Order".
    /// </example>
    StartsWith,
    /// <summary>
    /// Matches if the transaction description ends with the pattern.
    /// </summary>
    /// <example>
    /// Pattern: "ONLINE" matches "Purchase ONLINE" but not "Online Store".
    /// </example>
    EndsWith,
    /// <summary>
    /// Matches if the transaction description exactly equals the pattern.
    /// </summary>
    /// <example>
    /// Pattern: "NETFLIX" matches "NETFLIX" but not "Netflix Subscription".
    /// </example>
    Equals
}

/// <summary>
/// Provides helper methods for working with auto-categorization rules.
/// </summary>
public static class RuleHelper
{
    // Helper methods can be added here as needed for rule processing and validation.
}
