using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MoneyManager.Api.Data;

/// <summary>
/// Represents a financial transaction in the MoneyManager system.
/// </summary>
/// <remarks>
/// Transactions can be imported from bank CSV files or manually created.
/// They support auto-categorization through rules and can be linked to accounts and categories.
/// Amount is always stored as positive; direction is indicated by <see cref="IsDebit"/> property.
/// </remarks>
public class Transaction
{
    /// <summary>
    /// Gets or sets unique identifier for transaction.
    /// </summary>
    /// <value>
    /// The primary key for transaction entity. This value is auto-generated by the database.
    /// </value>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the account associated with this transaction.
    /// </summary>
    /// <value>
    /// The <see cref="Account"/> from which money was debited or to which it was credited.
    /// </value>
    /// <remarks>
    /// This is a required property and establishes a many-to-one relationship with the Accounts table.
    /// Transactions are filtered by account in many views and reports.
    /// </remarks>
    public Account Account { get; set; } = null!;

    /// <summary>
    /// Gets or sets the date when the transaction occurred.
    /// </summary>
    /// <value>
    /// The transaction date. For bank imports, this comes from the bank's record.
    /// </value>
    /// <remarks>
    /// Used for chronological ordering, date-based filtering, and charting.
    /// Time component may be included if available from the bank.
    /// </remarks>
    public DateTime Date { get; set; }

    /// <summary>
    /// Gets or sets the display description of the transaction.
    /// </summary>
    /// <value>
    /// A human-readable description of the transaction. May be modified by auto-categorization rules.
    /// </value>
    /// <remarks>
    /// This can differ from the original description if a rule was applied.
    /// Used for display in UI and for searching.
    /// </remarks>
    public string Description { get; set; } = null!;

    /// <summary>
    /// Gets or sets the original description of the transaction as imported from the bank.
    /// </summary>
    /// <value>
    /// The raw description from the bank's CSV export.
    /// </value>
    /// <remarks>
    /// This field is preserved for rule matching and duplicate detection.
    /// Never modified by the application after import.
    /// </remarks>
    public string OriginalDescription { get; set; } = null!;

    /// <summary>
    /// Gets or sets the absolute monetary amount of the transaction.
    /// </summary>
    /// <value>
    /// The transaction amount, always stored as a positive decimal value.
    /// </value>
    /// <remarks>
    /// Direction (income vs expense) is determined by the <see cref="IsDebit"/> property.
    /// For example, a $50 purchase stores Amount = 50, IsDebit = true.
    /// A $100 salary deposit stores Amount = 100, IsDebit = false.
    /// </remarks>
    public decimal Amount { get; set; }

    /// <summary>
    /// Gets the extended amount representing the signed value of the transaction.
    /// </summary>
    /// <value>
    /// Positive for income, negative for expenses. Calculated as -Amount if debit, +Amount if credit.
    /// </value>
    /// <remarks>
    /// This computed property is used for financial calculations and charting where signed values are needed.
    /// Formula: <c>IsDebit ? -Amount : Amount</c>
    /// </remarks>
    public decimal AmountExt => IsDebit ? -Amount : Amount;

    /// <summary>
    /// Gets or sets a value indicating whether this transaction represents a debit (expense) or credit (income).
    /// </summary>
    /// <value>
    /// <c>true</c> if the transaction is an expense (debit); <c>false</c> if it's income (credit).
    /// </value>
    /// <remarks>
    /// This boolean, combined with the positive <see cref="Amount"/> property, determines the transaction's direction.
    /// Debit transactions increase expenses; credit transactions increase income.
    /// </remarks>
    public bool IsDebit { get; set; }

    /// <summary>
    /// Gets or sets the category assigned to this transaction.
    /// </summary>
    /// <value>
    /// The <see cref="Category"/> for transaction classification, or null if not categorized.
    /// </value>
    /// <remarks>
    /// Categories are used for grouping and analyzing transactions in charts and reports.
    /// Transactions can be uncategorized (null) until manually categorized or auto-categorized by rules.
    /// The Transfer category is specifically filtered out from spending charts.
    /// </remarks>
    public Category? Category { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether an auto-categorization rule was applied to this transaction.
    /// </summary>
    /// <value>
    /// <c>true</c> if a rule was applied to this transaction; otherwise, <c>false</c>.
    /// </value>
    /// <remarks>
    /// Helps users distinguish between manual categorizations and automatic ones.
    /// This flag can be reset by the user to allow re-categorization.
    /// </remarks>
    public bool IsRuleApplied { get; set; }

    /// <summary>
    /// Returns a string representation of the transaction for display and debugging.
    /// </summary>
    /// <returns>
    /// A formatted string containing date, amount, rule applied indicator, and description.
    /// Format: "MM/DD/YYYY: $Amount [x] Description" (where [x] appears if rule applied).
    /// </returns>
    public override string ToString() => $"{Date:d}: {Amount:C} {(IsRuleApplied ? "[x] " : "")}{Description}";

    /// <summary>
    /// Converts this transaction to a Data Transfer Object (DTO) for UI binding.
    /// </summary>
    /// <returns>
    /// A <see cref="TransactionDto"/> containing all transaction properties including navigation properties.
    /// </returns>
    /// <remarks>
    /// DTOs are used to decouple database entities from UI components.
    /// This method includes the Transaction itself as a reference in the DTO.
    /// </remarks>
    public TransactionDto ToDto() => new()
    {
        Id = Id,
        Transaction = this,
        Account = Account,
        Date = Date,
        Description = Description,
        Amount = Amount,
        AmountExt = AmountExt,
        IsDebit = IsDebit,
        Category = Category,
        OriginalDescription = OriginalDescription,
    };
}

/// <summary>
/// Data Transfer Object for Transaction entity, used for UI binding.
/// </summary>
/// <remarks>
/// DTOs separate database entities from UI concerns.
/// This allows the UI to work with a simplified model while maintaining reference to the original entity.
/// </remarks>
public class TransactionDto
{
    /// <summary>
    /// Gets or sets the unique identifier of the transaction.
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets a reference to the original Transaction entity.
    /// </summary>
    /// <value>
    /// The actual <see cref="Transaction"/> entity this DTO represents.
    /// </value>
    /// <remarks>
    /// This allows direct access to the entity when needed for operations.
    /// </remarks>
    public Transaction Transaction { get; set; } = null!;

    /// <summary>
    /// Gets or sets the account associated with this transaction.
    /// </summary>
    public Account Account { get; set; } = null!;

    /// <summary>
    /// Gets or sets the date of the transaction.
    /// </summary>
    public DateTime Date { get; set; }

    /// <summary>
    /// Gets or sets the display description of the transaction.
    /// </summary>
    public string Description { get; set; } = null!;

    /// <summary>
    /// Gets or sets the original description from the bank import.
    /// </summary>
    public string OriginalDescription { get; set; } = null!;

    /// <summary>
    /// Gets or sets the absolute amount of the transaction.
    /// </summary>
    public decimal Amount { get; set; }

    /// <summary>
    /// Gets or sets the signed (extended) amount of the transaction.
    /// </summary>
    /// <value>
    /// Positive for income, negative for expenses.
    /// </value>
    public decimal AmountExt { get; set; }

    /// <summary>
    /// Gets or sets whether this transaction is a debit (expense) or credit (income).
    /// </summary>
    public bool IsDebit { get; set; }

    /// <summary>
    /// Gets or sets the category assigned to this transaction.
    /// </summary>
    public Category? Category { get; set; }

    /// <summary>
    /// Gets or sets whether an auto-categorization rule was applied.
    /// </summary>
    public bool IsRuleApplied { get; set; }

    /// <summary>
    /// Returns a string representation of the transaction DTO.
    /// </summary>
    /// <returns>
    /// A formatted string containing date, amount, rule applied indicator, and description.
    /// </returns>
    public override string ToString() => $"{Date:d}: {Amount:C} {(IsRuleApplied ? "[x] " : "")}{Description}";
}
